name: wedding
version: 0.0.1
id: 0a54e829-c352-4978-9291-c37f779e1900
description: "Wedding"
displayName:  Wedding Site

tags: wedding
providerDisplayName: wedding
longDescription: weding description
documentationURL: 
imageURL: https://cloud.google.com/_static/images/cloud/icons/favicons/onecloud/apple-icon.png
bindable: false
provisionOnlyOnce: true
