apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding
  template:
    metadata:
      labels:
        app: wedding
    spec:
      containers:
      - name: wedding
        image: docker.io/raphaelschmitz/weddding:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 4200
        env:
          - name: PORT
            value: "4200"
---
apiVersion: v1
kind: Service
metadata:
  name: wedding
  labels:
    app: wedding
spec:
  ports:
  - name: http
    port: 4200
  selector:
    app: wedding

